version: '3'
services:
    db-psql:
        container_name: "webrtc-postgres"
        image: postgres:12-alpine
        restart: always
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DB_NAME}
        volumes:
            - ./.docker/postgresql/data:/var/lib/postgresql/data
        ports:
            - ${PG_PORT}:5432

    db-redis:
        container_name: "webrtc-redis"
        image: redis
        restart: always
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - ./.docker/redis/data:/data
        ports:
            - ${REDIS_PORT}:6379
